import { ThemeRegistry } from './theme/theme';
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
    return (
        <html lang="ru">
            <head>
                <Script id="gtm-script-head" strategy="afterInteractive">
                    {`
                        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                        })(window,document,'script','dataLayer','GTM-WL56FFRB');
                    `}
                </Script>
                <title></title>
                <meta
                    name="description"
                    content="Купи стильный шарф и бант болельщика к матчу Кайрат - Реал Мадрид. Доставка по Казахстану 1–2 дня! Количество ограничено. Успей заказать прямо сейчас!"
                />
                <meta
                    name="keywords"
                    content="реал матч, кайрат матч, смотреть футбол, Реал Мадрид, лига чемпионов, уефа лига чемпионов, Кайрат, Центральный стадион, билеты, футбольная атрибутика, шарф болельщика, бант болельщика, купить шарф Кайрат, купить шарф , фанатский магазин, футбол Казахстан, футбол, футбол Алмата"
                />

                {/* OpenGraph (Facebook, LinkedIn, etc.) */}
                <meta property="og:title" content="Атрибутика к матчу Кайрат - Реал Мадрид" />
                <meta
                    property="og:description"
                    content="Купи стильный шарф и бант болельщика к матчу Кайрат - Реал Мадрид. Доставка по Казахстану 1–2 дня! Количество ограничено. Успей заказать прямо сейчас!"
                />
                <meta property="og:url" content="https://etobaza.kz/" />
                <meta property="og:site_name" content="etobaza.kz" />
                <meta property="og:type" content="website" />
                <meta property="og:locale" content="ru_RU" />

                {/* Twitter/X Card */}
                <meta name="twitter:card" content="summary_large_image" />
                <meta name="twitter:title" content="Атрибутика к матчу Кайрат - Реал Мадрид" />
                <meta
                    name="twitter:description"
                    content="Купи стильный шарф и бант болельщика к матчу Реал Мадрид - Кайрат. Доставка по Казахстану 1–2 дня! Количество ограничено. Успей заказать прямо сейчас!"
                />
                <meta name="twitter:url" content="https://etobaza.kz/" />
            </head>
            <body>
                <noscript>
                    <iframe
                        src="https://www.googletagmanager.com/ns.html?id=GTM-WL56FFRB"
                        height="0" width="0" style={{display: "none", visibility: "hidden"}}
                    />
                </noscript>
                <ThemeRegistry>
                    {children}
                </ThemeRegistry>
            </body>
        </html>
    );
}
